# Generated by Django 5.2.14 on 2026-06-03 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='contact_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='site',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='site',
            name='patrol_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='site',
            name='required_guards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='shift_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SiteEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='sites.site')),
            ],
            options={
                'ordering': ['site__name', 'priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('post_order', 'Post Order'), ('emergency', 'Emergency'), ('patrol', 'Patrol'), ('access_control', 'Access Control'), ('other', 'Other')], default='post_order', max_length=30)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='sites.site')),
            ],
            options={
                'ordering': ['site__name', 'title'],
            },
        ),
    ]
