# Generated by Django 5.2.14 on 2026-06-03 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('guards', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(db_index=True, max_length=80)),
                ('kind', models.CharField(choices=[('rfid', 'RFID'), ('gps', 'GPS')], default='rfid', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radius_meters', models.PositiveIntegerField(default=0)),
                ('event_codes', models.CharField(default='0', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='sites.site')),
            ],
            options={
                'ordering': ['site__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatrolRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrol_routes', to='sites.site')),
            ],
            options={
                'ordering': ['site__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatrolRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('usb', 'USB'), ('tcp', 'TCP/GPRS'), ('manual_import', 'Manual Import')], max_length=20)),
                ('source_record_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('device_number', models.CharField(blank=True, db_index=True, max_length=80)),
                ('imei', models.CharField(blank=True, db_index=True, max_length=80)),
                ('guard_identifier', models.CharField(blank=True, db_index=True, max_length=80)),
                ('checkpoint_identifier', models.CharField(blank=True, db_index=True, max_length=80)),
                ('record_type', models.CharField(blank=True, max_length=80)),
                ('occurred_at', models.DateTimeField()),
                ('information', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('satellites', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrol_records', to='patrols.checkpoint')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrol_records', to='devices.patroldevice')),
                ('guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrol_records', to='guards.guardprofile')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrol_records', to='patrols.patrolroute')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='PatrolRouteCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('expected_offset_minutes', models.PositiveIntegerField(default=0)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_steps', to='patrols.checkpoint')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_checkpoints', to='patrols.patrolroute')),
            ],
            options={
                'ordering': ['route', 'sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='checkpoint',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='unique_checkpoint_code_per_site'),
        ),
        migrations.AddConstraint(
            model_name='patrolroute',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='unique_route_code_per_site'),
        ),
        migrations.AddConstraint(
            model_name='patrolrecord',
            constraint=models.UniqueConstraint(fields=('source', 'device_number', 'source_record_id'), name='unique_source_device_record'),
        ),
        migrations.AddConstraint(
            model_name='patrolroutecheckpoint',
            constraint=models.UniqueConstraint(fields=('route', 'sequence'), name='unique_route_checkpoint_sequence'),
        ),
        migrations.AddConstraint(
            model_name='patrolroutecheckpoint',
            constraint=models.UniqueConstraint(fields=('route', 'checkpoint'), name='unique_checkpoint_per_route'),
        ),
    ]
