# Generated by Django 5.2.14 on 2026-06-03 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrols', '0001_initial'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exception_type', models.CharField(choices=[('missed_checkpoint', 'Missed Checkpoint'), ('late_checkpoint', 'Late Checkpoint'), ('wrong_sequence', 'Wrong Sequence'), ('device_not_synced', 'Device Not Synced')], max_length=40)),
                ('expected_at', models.DateTimeField(blank=True, null=True)),
                ('actual_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrol_exceptions', to='shifts.guardassignment')),
                ('checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrol_exceptions', to='patrols.checkpoint')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrol_exceptions', to='patrols.patrolroute')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'checkpoint', 'exception_type'), name='unique_patrol_exception_per_assignment_checkpoint_type')],
            },
        ),
    ]
