# Generated by Django 5.2.14 on 2026-06-14 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('guards', '0002_guardprofile_assigned_site_and_more'),
        ('patrols', '0002_patrolexception'),
        ('shifts', '0003_attendancerecord_unique_attendance_per_assignment'),
        ('sites', '0002_site_contact_name_site_contact_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardLiveState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('satellites', models.PositiveIntegerField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField()),
                ('last_record_type', models.CharField(blank=True, max_length=80)),
                ('last_checkpoint_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_states', to='shifts.guardassignment')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_state', to='devices.patroldevice')),
                ('guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_states', to='guards.guardprofile')),
                ('last_checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_guard_states', to='patrols.checkpoint')),
                ('last_patrol_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_state_updates', to='patrols.patrolrecord')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guard_live_states', to='sites.site')),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
