# Generated by Django 5.2.14 on 2026-06-03 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0001_initial'),
        ('sites', '0002_site_contact_name_site_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardprofile',
            name='assigned_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_guards', to='sites.site'),
        ),
        migrations.AddField(
            model_name='guardprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='guardprofile',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='guardprofile',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('on_duty', 'On Duty'), ('off_duty', 'Off Duty'), ('on_leave', 'On Leave'), ('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='DisciplinaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('occurred_on', models.DateField()),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_records', to='guards.guardprofile')),
            ],
            options={
                'ordering': ['guard__last_name', '-occurred_on'],
            },
        ),
        migrations.CreateModel(
            name='GuardDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('license', 'License'), ('certification', 'Certification'), ('training', 'Training'), ('other', 'Other')], max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='guards.guardprofile')),
            ],
            options={
                'ordering': ['guard__last_name', 'document_type'],
            },
        ),
        migrations.CreateModel(
            name='GuardNextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('relationship', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=40)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='guards.guardprofile')),
            ],
            options={
                'ordering': ['guard__last_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GuardTrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('provider', models.CharField(blank=True, max_length=160)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='guards.guardprofile')),
            ],
            options={
                'ordering': ['guard__last_name', '-completed_on'],
            },
        ),
        migrations.CreateModel(
            name='UniformIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(max_length=160)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('issued_on', models.DateField()),
                ('returned_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniform_issues', to='guards.guardprofile')),
            ],
            options={
                'ordering': ['guard__last_name', '-issued_on'],
            },
        ),
    ]
