# Generated by Django 5.2.14 on 2026-06-03 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('device_number', models.CharField(max_length=80, unique=True)),
                ('imei', models.CharField(blank=True, db_index=True, max_length=80)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('connection_mode', models.CharField(choices=[('usb', 'USB'), ('tcp', 'TCP/GPRS')], default='usb', max_length=20)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='registered', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sdk_metadata', models.JSONField(blank=True, default=dict)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='sites.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
