# Generated by Django 5.2.14 on 2026-06-03 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_clientcontact_clientcontract'),
        ('sites', '0002_site_contact_name_site_contact_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('daily_attendance', 'Daily Attendance'), ('duty_roster', 'Duty Roster'), ('patrol_completion', 'Patrol Completion'), ('missed_checkpoint', 'Missed Checkpoint'), ('incident', 'Incident'), ('supervisor_inspection', 'Supervisor Inspection'), ('client_service', 'Client Service'), ('device_usage', 'Device Usage'), ('guard_performance', 'Guard Performance'), ('site_performance', 'Site Performance')], max_length=40)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_url', models.URLField(blank=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_requests', to='clients.client')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_requests', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_requests', to='sites.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
